# Generated by Django 3.1.1 on 2020-12-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201205_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Clothes', 'Clothes'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
