# Generated by Django 3.1.1 on 2020-12-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201206_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
